#Config file for BukkitBoard (Pre-Alpha)

hostname: localhost
database: bb
user: bbtest
password: 12345
boards:
  - name: store
    tablename: stores
    aliases: - s
             - shops
  - name: clan
    tablename: clans
    aliases: - c
             - clan
             - clans
  - name: team
    tablename: teams
    aliases: - t
             - team
             - teams
  - name: faction
    tablename: factions
    aliases: - f
             - faction
             - fac
             - factions
